version: "3.8"

services:
  mongodb:
    image: mongo:latest
    env_file: .env
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: [--auth]

  app:
    container_name: footstats_app
    build: .
    command: "python3 main.py"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    env_file: .env
    depends_on:
      - mongodb

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379

  celery_worker:
    container_name: footstats_celery_worker
    build: .
    command: celery -A tasks.celery_app worker -l info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis

  flower:
    container_name: footstats_flower
    build: .
    command: celery -A tasks.celery_app flower --port=5555
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis
      - celery_worker


volumes:
  mongo_data:
