FROM node:alpine

# Setting working directory.
WORKDIR /app

# Copy package.json and package-log.json
COPY package*.json ./

# installing dependencies.
RUN npm i

# Copy the rest of the application code.
COPY . .
