# Generated by Django 4.2.13 on 2024-05-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_city_created_at_alter_city_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stats.continent'),
            preserve_default=False,
        ),
    ]
