# Generated by Django 4.2.13 on 2024-05-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_country_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.continent'),
        ),
    ]
