# Generated by Django 4.2.13 on 2024-05-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_tournamentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='tournament_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.tournamentcategory'),
        ),
    ]
