"""Event Timestamps Added.

Revision ID: 2d6be9b29f5b
Revises: d0852bdde2cc
Create Date: 2024-09-25 17:51:08.242713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2d6be9b29f5b'
down_revision: Union[str, None] = 'd0852bdde2cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_event', sa.Column('start_timestamp', sa.DateTime(), nullable=True))
    op.add_column('tournament_event', sa.Column('end_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_event', 'end_timestamp')
    op.drop_column('tournament_event', 'start_timestamp')
    # ### end Alembic commands ###
