"""init

Revision ID: 42405894344d
Revises: 
Create Date: 2024-08-22 18:55:27.247461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42405894344d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('sofascore_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False
                    ),
                    sa.Column(
                        'slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True
                    ),
                    sa.PrimaryKeyConstraint('sofascore_id')
                    )
    op.create_table('team',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('sofascore_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(),
                        nullable=False),
                    sa.Column('name_code', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.Column(
                        'country', sqlmodel.sql.sqltypes.AutoString(),
                        nullable=True),
                    sa.Column('ranking', sa.Integer(), nullable=True),
                    sa.Column(
                        'slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('sofascore_id')
                    )
    op.create_table('tournament',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('sofascore_id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('has_standings_groups',
                              sa.Boolean(), nullable=False),
                    sa.Column('has_groups', sa.Boolean(), nullable=False),
                    sa.Column('has_rounds', sa.Boolean(), nullable=False),
                    sa.Column('has_playoff_series',
                              sa.Boolean(), nullable=False),
                    sa.Column('sofascore_link',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
                    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['category.sofascore_id'], ),
                    sa.PrimaryKeyConstraint('sofascore_id')
                    )
    op.create_table('tournament_season',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('sofascore_id', sa.Integer(), nullable=False),
                    sa.Column('tournament_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['tournament_id'], ['tournament.sofascore_id'], ),
                    sa.PrimaryKeyConstraint('sofascore_id')
                    )
    op.create_table('tournament_group',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('sofascore_id', sa.Integer(), nullable=False),
                    sa.Column('tournament_season_id',
                              sa.Integer(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['tournament_season_id'], [
                        'tournament_season.sofascore_id'], ),
                    sa.PrimaryKeyConstraint('sofascore_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_group')
    op.drop_table('tournament_season')
    op.drop_table('tournament')
    op.drop_table('team')
    op.drop_table('category')
    # ### end Alembic commands ###
