"""Event status fields.

Revision ID: 543ff9cffeb5
Revises: 1bc1c912f586
Create Date: 2024-09-24 21:21:17.123008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '543ff9cffeb5'
down_revision: Union[str, None] = '1bc1c912f586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_event', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('tournament_event', sa.Column('status_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tournament_event', sa.Column('status_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tournament_event', sa.Column('home_score_current', sa.Integer(), nullable=False))
    op.add_column('tournament_event', sa.Column('away_score_current', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_event', 'away_score_current')
    op.drop_column('tournament_event', 'home_score_current')
    op.drop_column('tournament_event', 'status_type')
    op.drop_column('tournament_event', 'status_description')
    op.drop_column('tournament_event', 'status_code')
    # ### end Alembic commands ###
