"""Team event foreignkey26.

Revision ID: 611a1d8f71e8
Revises: 4cade00828e7
Create Date: 2024-08-24 22:06:13.879672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '611a1d8f71e8'
down_revision: Union[str, None] = '4cade00828e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
