"""Team event foreignkekes.

Revision ID: 98d2ac03fd40
Revises: b8d6a2924a1f
Create Date: 2024-08-23 21:55:52.206138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98d2ac03fd40'
down_revision: Union[str, None] = 'b8d6a2924a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
