"""Primary key Changes.

Revision ID: af7f56a5cdda
Revises: 42405894344d
Create Date: 2024-08-22 22:07:33.675474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af7f56a5cdda'
down_revision: Union[str, None] = '42405894344d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_event',
    sa.Column('sofascore_id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('detail_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score_period_1', sa.Integer(), nullable=False),
    sa.Column('home_score_period_2', sa.Integer(), nullable=False),
    sa.Column('home_score_normaltime', sa.Integer(), nullable=False),
    sa.Column('home_score_extratime', sa.Integer(), nullable=False),
    sa.Column('home_score_penalties', sa.Integer(), nullable=False),
    sa.Column('away_score_period_1', sa.Integer(), nullable=False),
    sa.Column('away_score_period_2', sa.Integer(), nullable=False),
    sa.Column('away_score_normaltime', sa.Integer(), nullable=False),
    sa.Column('away_score_extratime', sa.Integer(), nullable=False),
    sa.Column('away_score_penalties', sa.Integer(), nullable=False),
    sa.Column('has_xg', sa.Boolean(), nullable=False),
    sa.Column('has_eventplayer_statistics', sa.Boolean(), nullable=False),
    sa.Column('has_eventplayer_heatmap', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.sofascore_id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.sofascore_id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['tournament_group.sofascore_id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.sofascore_id'], ),
    sa.PrimaryKeyConstraint('sofascore_id', 'id')
    )
    op.create_index(op.f('ix_tournament_event_id'), 'tournament_event', ['id'], unique=False)
    op.add_column('category', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.add_column('team', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.add_column('tournament', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_tournament_id'), 'tournament', ['id'], unique=False)
    op.add_column('tournament_group', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_tournament_group_id'), 'tournament_group', ['id'], unique=False)
    op.add_column('tournament_season', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_tournament_season_id'), 'tournament_season', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_season_id'), table_name='tournament_season')
    op.drop_column('tournament_season', 'id')
    op.drop_index(op.f('ix_tournament_group_id'), table_name='tournament_group')
    op.drop_column('tournament_group', 'id')
    op.drop_index(op.f('ix_tournament_id'), table_name='tournament')
    op.drop_column('tournament', 'id')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_column('team', 'id')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_column('category', 'id')
    op.drop_index(op.f('ix_tournament_event_id'), table_name='tournament_event')
    op.drop_table('tournament_event')
    # ### end Alembic commands ###
