"""Team event foreignkey22.

Revision ID: fdb8704f1bb1
Revises: 98d2ac03fd40
Create Date: 2024-08-23 21:56:50.213797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdb8704f1bb1'
down_revision: Union[str, None] = '98d2ac03fd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
